name: Cross compile

on:
  push:
    tags:
      - v.*
    branches:
      - releases
jobs:
  compile:
    name: "Compile - ${{matrix.platform.os-name}}"
    strategy:
      matrix:
        platform:
          - os-name: macos-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
          - os-name: macOS-arm
            runs-on: macOS-latest
            target: aarch64-apple-darwin
          - os-name: linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
    runs-on: ${{matrix.platform.runs-on}}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@9a1618ffb70e8374ab5f48fcccea3ebeacf57971
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: docker-compose-k8s-provider
          target: ${{ matrix.platform.target }}